/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardLogsRouteImport } from './routes/dashboard/logs'
import { Route as DashboardBookIndexRouteImport } from './routes/dashboard/book/index'
import { Route as DashboardBookIDRouteImport } from './routes/dashboard/book/$ID'

const LoginLazyRouteImport = createFileRoute('/login')()

const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBookIndexRoute = DashboardBookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBookIDRoute = DashboardBookIDRouteImport.update({
  id: '/book/$ID',
  path: '/book/$ID',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/book/$ID': typeof DashboardBookIDRoute
  '/dashboard/book': typeof DashboardBookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginLazyRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/book/$ID': typeof DashboardBookIDRoute
  '/dashboard/book': typeof DashboardBookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/book/$ID': typeof DashboardBookIDRoute
  '/dashboard/book/': typeof DashboardBookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/logs'
    | '/dashboard/'
    | '/dashboard/book/$ID'
    | '/dashboard/book'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/logs'
    | '/dashboard'
    | '/dashboard/book/$ID'
    | '/dashboard/book'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/logs'
    | '/dashboard/'
    | '/dashboard/book/$ID'
    | '/dashboard/book/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginLazyRoute: typeof LoginLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/book/': {
      id: '/dashboard/book/'
      path: '/book'
      fullPath: '/dashboard/book'
      preLoaderRoute: typeof DashboardBookIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/book/$ID': {
      id: '/dashboard/book/$ID'
      path: '/book/$ID'
      fullPath: '/dashboard/book/$ID'
      preLoaderRoute: typeof DashboardBookIDRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBookIDRoute: typeof DashboardBookIDRoute
  DashboardBookIndexRoute: typeof DashboardBookIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBookIDRoute: DashboardBookIDRoute,
  DashboardBookIndexRoute: DashboardBookIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginLazyRoute: LoginLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
